# Generated by Django 2.1.7 on 2019-04-18 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mton', '0005_auto_20190418_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='credits',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='lecture_time',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='students',
        ),
        migrations.RemoveField(
            model_name='student',
            name='account',
        ),
        migrations.RemoveField(
            model_name='student',
            name='major',
        ),
    ]
